package com.gogrameen.app.catalogue

/* GENERATED FILE -- DO NOT EDIT BY HAND.
 *
 * Regenerate with scripts/gen-android-produce-names.py, which reads
 * src/lib/produceNamesTe.ts. Edit the crop names there, never here, so the
 * web and the app cannot disagree about what a crop is called.
 *
 * 220 entries. */

internal val PRODUCE_NAME_TE: Map<String, String> = mapOf(
    "aavalu" to "ఆవాలు",
    "aavu neyyi" to "ఆవు నెయ్యి",
    "alasandalu" to "అలసందలు",
    "allam" to "అల్లం",
    "amaranth" to "తోటకూర",
    "apple" to "ఆపిల్",
    "aratikaya" to "అరటికాయ",
    "aratipandu" to "అరటిపండు",
    "asafoetida" to "ఇంగువ",
    "ash gourd" to "బూడిద గుమ్మడికాయ",
    "bachalikura" to "బచ్చలికూర",
    "bajra" to "సజ్జలు",
    "banana" to "అరటిపండు",
    "bangaladumpa" to "బంగాళాదుంప",
    "batayi" to "బత్తాయి",
    "battayi" to "బత్తాయి",
    "beans" to "చిక్కుడు",
    "beerakaya" to "బీరకాయ",
    "beetroot" to "బీట్‌రూట్",
    "bell pepper" to "క్యాప్సికం",
    "bellam" to "బెల్లం",
    "bendakaya" to "బెండకాయ",
    "betel leaf" to "తమలపాకు",
    "bitter gourd" to "కాకరకాయ",
    "biyyam" to "బియ్యం",
    "black eyed pea" to "అలసందలు",
    "black gram" to "మినుములు",
    "black pepper" to "మిరియాలు",
    "bobbarlu" to "బొబ్బర్లు",
    "boppayi" to "బొప్పాయి",
    "bottle gourd" to "సొరకాయ",
    "brinjal" to "వంకాయ",
    "butter" to "వెన్న",
    "buttermilk" to "మజ్జిగ",
    "cabbage" to "క్యాబేజీ",
    "capsicum" to "క్యాప్సికం",
    "cardamom" to "యాలకులు",
    "carrot" to "క్యారెట్",
    "cashew" to "జీడిపప్పు",
    "cauliflower" to "కాలీఫ్లవర్",
    "chamadumpa" to "చామదుంప",
    "chana" to "శనగలు",
    "chickpea" to "శనగలు",
    "chikkudu" to "చిక్కుడు",
    "chilagadadumpa" to "చిలగడదుంప",
    "chilli" to "మిరప",
    "chilli powder" to "మిరప పొడి",
    "chintapandu" to "చింతపండు",
    "chukkakura" to "చుక్కకూర",
    "cinnamon" to "దాల్చిన చెక్క",
    "clove" to "లవంగాలు",
    "cluster beans" to "గోరు చిక్కుడు",
    "coconut" to "కొబ్బరి",
    "colocasia" to "చామదుంప",
    "coriander" to "కొత్తిమీర",
    "coriander seed" to "ధనియాలు",
    "corn" to "మొక్కజొన్న",
    "cow ghee" to "ఆవు నెయ్యి",
    "cowpea" to "బొబ్బర్లు",
    "cucumber" to "దోసకాయ",
    "cumin" to "జీలకర్ర",
    "curd" to "పెరుగు",
    "curry leaf" to "కరివేపాకు",
    "curry leaves" to "కరివేపాకు",
    "custard apple" to "సీతాఫలం",
    "dal" to "పప్పు",
    "danimma" to "దానిమ్మ",
    "dhaniyalu" to "ధనియాలు",
    "dill" to "సోంపు ఆకు",
    "dondakaya" to "దొండకాయ",
    "dosakaya" to "దోసకాయ",
    "draksha" to "ద్రాక్ష",
    "drumstick" to "మునగకాయ",
    "drumstick leaves" to "మునగాకు",
    "egg" to "గుడ్డు",
    "eggplant" to "వంకాయ",
    "eggs" to "గుడ్లు",
    "fennel" to "సోంపు",
    "fenugreek" to "మెంతులు",
    "fenugreek leaves" to "మెంతికూర",
    "fenugreek seed" to "మెంతులు",
    "fig" to "అంజీర",
    "garlic" to "వెల్లుల్లి",
    "ghee" to "నెయ్యి",
    "ginger" to "అల్లం",
    "godhuma" to "గోధుమ",
    "gongura" to "గోంగూర",
    "goru chikkudu" to "గోరు చిక్కుడు",
    "grapes" to "ద్రాక్ష",
    "green chilli" to "పచ్చిమిర్చి",
    "green gram" to "పెసలు",
    "green leaf" to "ఆకుకూర",
    "greens" to "ఆకుకూరలు",
    "groundnut" to "వేరుశనగ",
    "guava" to "జామ",
    "gudlu" to "గుడ్లు",
    "gummadikaya" to "గుమ్మడికాయ",
    "honey" to "తేనె",
    "horse gram" to "ఉలవలు",
    "ivy gourd" to "దొండకాయ",
    "jackfruit" to "పనసకాయ",
    "jaggery" to "బెల్లం",
    "jama" to "జామ",
    "jeelakarra" to "జీలకర్ర",
    "jonna" to "జొన్న",
    "jonnalu" to "జొన్నలు",
    "jowar" to "జొన్న",
    "kakarakaya" to "కాకరకాయ",
    "kanda" to "కంద",
    "kandi pappu" to "కందిపప్పు",
    "kandulu" to "కందులు",
    "karivepaku" to "కరివేపాకు",
    "kobbari" to "కొబ్బరి",
    "kothimeera" to "కొత్తిమీర",
    "lady finger" to "బెండకాయ",
    "lemon" to "నిమ్మ",
    "lemongrass" to "నిమ్మగడ్డి",
    "lentil" to "పప్పు",
    "lime" to "నిమ్మ",
    "maize" to "మొక్కజొన్న",
    "majjiga" to "మజ్జిగ",
    "mamidi" to "మామిడి",
    "mango" to "మామిడి",
    "menthikura" to "మెంతికూర",
    "menthulu" to "మెంతులు",
    "methi" to "మెంతికూర",
    "milk" to "పాలు",
    "millet" to "చిరుధాన్యం",
    "millets" to "చిరుధాన్యాలు",
    "mint" to "పుదీన",
    "minumulu" to "మినుములు",
    "mirapakaya" to "మిరపకాయ",
    "miriyalu" to "మిరియాలు",
    "mokkajonna" to "మొక్కజొన్న",
    "moong" to "పెసలు",
    "moringa" to "మునగాకు",
    "mosambi" to "బత్తాయి",
    "mullangi" to "ముల్లంగి",
    "munagakaya" to "మునగకాయ",
    "muskmelon" to "ఖర్బూజా",
    "mustard" to "ఆవాలు",
    "neyyi" to "నెయ్యి",
    "nimma" to "నిమ్మ",
    "nutmeg" to "జాజికాయ",
    "nuvvulu" to "నువ్వులు",
    "okra" to "బెండకాయ",
    "onion" to "ఉల్లిపాయ",
    "orange" to "నారింజ",
    "paalu" to "పాలు",
    "pachi mirapakaya" to "పచ్చిమిరపకాయ",
    "pachimirchi" to "పచ్చిమిర్చి",
    "palak" to "పాలకూర",
    "palakura" to "పాలకూర",
    "palli" to "పల్లీలు",
    "panasa" to "పనస",
    "paneer" to "పన్నీర్",
    "papaya" to "బొప్పాయి",
    "pasupu" to "పసుపు",
    "peanut" to "వేరుశనగ",
    "peas" to "బఠానీలు",
    "pepper" to "మిరియాలు",
    "perugu" to "పెరుగు",
    "pesalu" to "పెసలు",
    "pineapple" to "అనాసపండు",
    "pomegranate" to "దానిమ్మ",
    "potato" to "బంగాళాదుంప",
    "potlakaya" to "పొట్లకాయ",
    "puchakaya" to "పుచ్చకాయ",
    "pudina" to "పుదీన",
    "pulses" to "పప్పుధాన్యాలు",
    "pumpkin" to "గుమ్మడికాయ",
    "radish" to "ముల్లంగి",
    "ragi" to "రాగులు",
    "ragulu" to "రాగులు",
    "raw banana" to "అరటికాయ",
    "red chilli" to "ఎండు మిరప",
    "red gram" to "కందిపప్పు",
    "rice" to "బియ్యం",
    "ridge gourd" to "బీరకాయ",
    "sajjalu" to "సజ్జలు",
    "sapota" to "సపోటా",
    "senagalu" to "శనగలు",
    "sesame" to "నువ్వులు",
    "sitaphalam" to "సీతాఫలం",
    "snake gourd" to "పొట్లకాయ",
    "sorakaya" to "సొరకాయ",
    "sorrel" to "గోంగూర",
    "spinach" to "పాలకూర",
    "spring onion" to "ఉల్లికాడ",
    "strawberry" to "స్ట్రాబెర్రీ",
    "sugarcane" to "చెరకు",
    "sweet lime" to "బత్తాయి",
    "sweet potato" to "చిలగడదుంప",
    "tamarind" to "చింతపండు",
    "tamata" to "టమాటా",
    "tamota" to "టమాటా",
    "tapioca" to "కర్రపెండలం",
    "taro" to "చామదుంప",
    "tender coconut" to "కొబ్బరి బొండాం",
    "tene" to "తేనె",
    "thotakura" to "తోటకూర",
    "tindora" to "దొండకాయ",
    "tomato" to "టమాటా",
    "toor" to "కందిపప్పు",
    "toor dal" to "కందిపప్పు",
    "turmeric" to "పసుపు",
    "turmeric powder" to "పసుపు పొడి",
    "ulavalu" to "ఉలవలు",
    "ulligadda" to "ఉల్లిగడ్డ",
    "ullipaya" to "ఉల్లిపాయ",
    "urad" to "మినుములు",
    "vamu" to "వాము",
    "vankaya" to "వంకాయ",
    "vellulli" to "వెల్లుల్లి",
    "venna" to "వెన్న",
    "verusenaga" to "వేరుశనగ",
    "watermelon" to "పుచ్చకాయ",
    "wheat" to "గోధుమ",
    "yaalakulu" to "యాలకులు",
    "yam" to "కంద",
)
