package com.gogrameen.app.catalogue

import com.gogrameen.app.Lang
import org.junit.Assert.assertEquals
import org.junit.Test

/* The produce-name rules, ported from src/lib/localizeName.ts.
 *
 * Every name below is a real one from the live catalogue. That matters: the
 * intended storage form is "English / తెలుగు" and NOT ONE live listing uses it
 * — they are all either plain English or the "Aavu Neyyi - Cow ghee" segment
 * form. A test suite built on the documented format would have passed while the
 * Telugu toggle did nothing to the real data. */
class LocalizeTest {

    @Test
    fun `the slash form takes the matching side`() {
        assertEquals("Tomato", localizeName("Tomato / టమాటా", Lang.EN))
        assertEquals("టమాటా", localizeName("Tomato / టమాటా", Lang.TE))
    }

    @Test
    fun `a dictionary name is translated on its own`() {
        assertEquals("పసుపు", localizeName("Turmeric", Lang.TE))
        assertEquals("Turmeric", localizeName("Turmeric", Lang.EN))
    }

    @Test
    fun `lookup ignores case and surrounding space`() {
        assertEquals("మామిడి", localizeName("  MANGO  ", Lang.TE))
    }

    @Test
    fun `both halves of a bilingual segment name collapse to one`() {
        // "Aavu Neyyi" and "Cow ghee" both map to ఆవు నెయ్యి. Printing the pair
        // would give "ఆవు నెయ్యి - ఆవు నెయ్యి", which reads as a bug.
        assertEquals("ఆవు నెయ్యి", localizeName("Aavu Neyyi - Cow ghee", Lang.TE))
    }

    @Test
    fun `an unknown qualifier survives translation`() {
        // Half-guessing a product name is worse than leaving it as the farmer
        // wrote it, so the segment the dictionary does not know is kept.
        assertEquals("టమాటా - Country", localizeName("Tomato - Country", Lang.TE))
    }

    @Test
    fun `a name nothing resolves comes back untouched`() {
        // Live listing. Neither segment is in the dictionary, so the name must
        // not be partially rewritten or reordered.
        val name = "Bahuroopi Rice - Single Polish"
        assertEquals(name, localizeName(name, Lang.TE))
        assertEquals(name, localizeName(name, Lang.EN))
    }

    @Test
    fun `english never consults the dictionary`() {
        // The EN branch is a straight passthrough. A dictionary hit leaking into
        // English would show Telugu to a reader who asked for English.
        for (name in listOf("Turmeric", "Aavu Neyyi - Cow ghee", "Mango")) {
            assertEquals(name, localizeName(name, Lang.EN))
        }
    }

    @Test
    fun `a missing name is empty, not the word null`() {
        assertEquals("", localizeName(null, Lang.TE))
        assertEquals("", localizeName("   ", Lang.EN))
    }

    @Test
    fun `units translate and unknown units are left alone`() {
        assertEquals("కేజీ", localizeUnit("kg", Lang.TE))
        assertEquals("నగ", localizeUnit("piece", Lang.TE))
        assertEquals("kg", localizeUnit("kg", Lang.EN))
        assertEquals("crate", localizeUnit("crate", Lang.TE))
        assertEquals("", localizeUnit(null, Lang.TE))
    }

    @Test
    fun `the generated dictionary is actually populated`() {
        // ProduceNamesTe.kt is generated by a script that could silently emit an
        // empty map if the TypeScript source were reformatted. Every name would
        // then quietly fall back to English with no other test failing.
        assert(PRODUCE_NAME_TE.size > 150) { "dictionary looks truncated: ${PRODUCE_NAME_TE.size}" }
    }
}
